/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.almond.dialogs.cron;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class CronPanel extends javax.swing.JPanel {

    /**
     * Creates new form CronPanel
     */
    public CronPanel() {
        initComponents();
    }

    public String getCronString() {
        return "*";
    }

    public void setCronString(String cronString) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elementMinutePanel1 = new se.trixon.almond.dialogs.cron.ElementMinutePanel();
        elementHourPanel1 = new se.trixon.almond.dialogs.cron.ElementHourPanel();
        elementDomPanel1 = new se.trixon.almond.dialogs.cron.ElementDomPanel();
        elementMonthPanel1 = new se.trixon.almond.dialogs.cron.ElementMonthPanel();
        elementDowPanel1 = new se.trixon.almond.dialogs.cron.ElementDowPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        elementMinutePanel1.setText(org.openide.util.NbBundle.getMessage(CronPanel.class, "CronPanel.elementMinutePanel1.text")); // NOI18N
        add(elementMinutePanel1);

        elementHourPanel1.setText(org.openide.util.NbBundle.getMessage(CronPanel.class, "CronPanel.elementHourPanel1.text")); // NOI18N
        add(elementHourPanel1);

        elementDomPanel1.setText(org.openide.util.NbBundle.getMessage(CronPanel.class, "CronPanel.elementDomPanel1.text")); // NOI18N
        add(elementDomPanel1);

        elementMonthPanel1.setText(org.openide.util.NbBundle.getMessage(CronPanel.class, "CronPanel.elementMonthPanel1.text")); // NOI18N
        add(elementMonthPanel1);

        elementDowPanel1.setText(org.openide.util.NbBundle.getMessage(CronPanel.class, "CronPanel.elementDowPanel1.text")); // NOI18N
        add(elementDowPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.almond.dialogs.cron.ElementDomPanel elementDomPanel1;
    private se.trixon.almond.dialogs.cron.ElementDowPanel elementDowPanel1;
    private se.trixon.almond.dialogs.cron.ElementHourPanel elementHourPanel1;
    private se.trixon.almond.dialogs.cron.ElementMinutePanel elementMinutePanel1;
    private se.trixon.almond.dialogs.cron.ElementMonthPanel elementMonthPanel1;
    // End of variables declaration//GEN-END:variables
}
